### PR TITLE
Add kotlin and gradle support

### PR DESCRIPTION
**Pull request by Torbacka**
Have also converted the project to use the maven standard directory layout. So it will be easier to extend  the project in the future. 

I added a dependency to [reflections](https://github.com/ronmamo/reflections). This dependencies make it possible to find all classes belonging to package. It made it easier support gradle and ant at the same time.

### CODE REVIEW

**Comment by mantono** [comment]
This closes #9 (sort of).

**Comment by Xanindorf** [comment]
Thank you for your interest and your contribution. We are discussing these changes within the team and will get back to you as soon as possible.

**Comment by rloqvist** [comment]
Merged these changes to my PR according to the new travis changes.

**Comment by booski** [comment]
We like the intent of this pull request, but can't accept it in its current form two main reasons:
1) It is too big. This PR does very many things, which makes it hard to get a clear overview of the proposed changes, how they relate to each other and any potential consequences.
2) It breaks conventions used in the rest of the code. All indentation is done using tabs, when the rest of the project uses spaces. The new brain import code also completely breaks with the prevailing style, opting for highly compact code instead of the very verbose and 'spread out' style used in the rest of the project. Neither of these points are general criticisms of either of those two choices, but rather a matter of keeping with the style of existing code and keeping the code 'clean' and easily read.

If you could split this PR into several chunks, we would probably integrate most of it. I would suggest splitting by a slightly loose definition of feature - something like this:
 - Kotlin support
 - Gradle support
 - Maven directory structure
 - Brain import refactoring
 - Probably further things that I have forgotten/not noticed

I'm closing this PR since this iteration won't be merged, but please don't view that as rejecting your proposed changes, we just want the proposal(s) in more easily digestible chunks.

**Comment by Torbacka** [comment]
Then I will split it to smaller changes and starting with gradle support

**Pull request closed without merging**
